---

- name: Test
  hosts: agent5_linux
  become: true  # optional
  any_errors_fatal: true
  gather_facts: true


  vars:
    msg1: Hello
    msg2: World
    number2: 2
    source: test_confi.ini.j2
    dest: /tmp/config.ini


  tasks:
    - name: Import
      include_vars:
        file: vault_vars.yml
    
    - include_role:
        name: deploy_apache
    
    # - name: Setup #optinal
    #   debug:
    #     msg: "msg1 = {{ msg1 }}, msg2 = {{ msg2 }}"

    # - debug:
    #     var: ansible_os_family

    # - name: Run shell uptime
    #   shell:
    #     uptime
    #   register:
    #     result

    # - debug:
    #     msg: " Shell comand resut = {{ result.stdout }} "
