# [atlanta]
# host1
# host2

# [atlanta:vars]
# ntp_server=ntp.atlanta.example.com
# proxy=proxy.atlanta.example.com



atlanta:
  hosts:
    host1:
    host2:
  vars:
    ntp_server: ntp.atlanta.example.com
    proxy: proxy.atlanta.example.com

